version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
          - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: .
    restart: always
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A core flower
    ports:
      - "0.0.0.0:5555:5555"
    depends_on:
      - celery