# Generated by Django 4.1.1 on 2022-09-18 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong number format. Number format should be 7XXXXXXXXX (X - number from 0 to 9)', regex='^7\\d{10}$')], verbose_name='phone number')),
                ('mobile_operator_code', models.CharField(max_length=3, verbose_name='mobile operator code')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='tag')),
                ('time_zone', models.CharField(blank=True, max_length=100, verbose_name='time zone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('text', models.TextField(verbose_name='text')),
                ('user_filter_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='tag filter')),
                ('user_filter_phone_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='code filter')),
                ('finish_time', models.DateTimeField(verbose_name='finish time')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('not sent', 'NOT SENT')], max_length=8, verbose_name='status sending')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notification_service.client', verbose_name='client')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notification_service.mailinglist', verbose_name='mailing list')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
